---
driver:
  name: docker
  privileged: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7
    driver:
      image: roboticcheese/centos-7-systemd
  - name: centos-6
  - name: centos-5
